version: '3.1'

services:
  editor:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: ngUML.editor
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true