# Generated by Django 3.2.13 on 2022-09-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_rename_extractionresult_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200)),
                ('uuid', models.UUIDField()),
                (
                    'bucket',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='jobs',
                        to='extraction.bucket',
                    ),
                ),
                (
                    'requirement',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='jobs',
                        to='extraction.requirement',
                    ),
                ),
            ],
        ),
    ]
