# Generated by Django 3.2.13 on 2022-09-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='model',
            field=models.CharField(
                choices=[
                    ('CLASS', 'UML Class Model'),
                    ('USECASE', 'UML Use Case Model'),
                    ('COMPONENT', 'UML Component Model'),
                    ('ACTIVITY', 'UML Activity Model'),
                    ('BUCKET', 'Bucketing'),
                ],
                default='CLASS',
                max_length=20,
            ),
        ),
    ]
