# Generated by Django 3.2.13 on 2022-10-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0005_alter_job_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
